/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DNS1.h"

int util=0;
int redutil=1;
char valores[50][3][255];

char redes[50][2][255];

char redusada[10]="DNS1";


char **
introducir_1_svc(nombre arg1, red arg2, ip arg3,  struct svc_req *rqstp)
{
	static char * result;
 	if(strcmp(arg2,redusada)==0){
		strcpy(valores[util][0],arg1);
 		strcpy(valores[util][1],arg2);
 		strcpy(valores[util][2],arg3);
 		util++;
 		printf("%s\n", "HA SIDO INTRODUCIDO");
		result="HA SIDO INTRODUCIDO";
 	}
 	else{
 		printf("%s\n", "ESTA ES LA RED1, INTRODUCE LOS VALORES USANDO Red1");
		result="ESTA ES LA RED1, INTRODUCE LOS VALORES USANDO Red1";
 	}
	return &result;
}

char **
eliminar_1_svc(nombre arg1, red arg2,  struct svc_req *rqstp)
{
	static char * result;

	int i=0;
	int encontrado=999;
	if(strcmp(arg2,redusada)==0){
		for(i;i<util;i++){
			if(strcmp(arg1,valores[i][0])==0){
				encontrado=i;
			}
		}
		if(encontrado!=999){ //Tiene nombre y red correctos borramos la posición
			for(encontrado;encontrado<util;encontrado++){
				strcpy(valores[encontrado][0],valores[encontrado+1][0]);
				strcpy(valores[encontrado][1],valores[encontrado+1][1]);
				strcpy(valores[encontrado][2],valores[encontrado+1][2]);
			}
			strcpy(valores[util][0],"0");
			strcpy(valores[util][1],"0");
			strcpy(valores[util][2],"0");
			util--;
			encontrado=999;
      printf("%s\n", "BORRADO correctamente");
			result="BORRADO CORRECTAMENTE";
		}
		else{
			printf("%s\n", "NOMBRE NO encontrado");
			result="NOMBRE NO ENCONTRADO";
		}
	}
 	else{
		printf("%s\n", "ESTA ES LA RED1, INTRODUCE LOS VALORES USANDO Red1");
		result="ESTA ES LA RED 1, INTRODUCE VALORES USANDO Red1";
 	}

	return &result;
}

char **
consultar_1_svc(nombre arg1, red arg2,  struct svc_req *rqstp)
{
	static char * result;
	static char * prueba;
		int encontrado=999;
	result="NO ENCONTRADO POR ESE NOMBRE EN ESTA RED";
  int i=0;
	for(i;i<redutil;i++){
		if(strcmp(arg1,redes[i][0])==0){
			encontrado=i;
		}
	}
	if(encontrado!=999){
		for(i;i<util;i++){
	  	if(strcmp(arg1,valores[i][0])==0){


					result = valores[i][2];
	        return &result;
	    }
	  }
	}
	else{
		CLIENT *clnt2;
	  char * *result_1;

		#ifndef	DEBUG
		clnt2 = clnt_create ("localhost", redes[encontrado][1], DNSVERS, "udp"); //Problema debido a que redes[encontradp][1] nos da una cadena de char y no un u_long ya que cuando lo definiamos en el .h cogia el valor correcto
		if (clnt2 == NULL) {
			clnt_pcreateerror ("localhost");
			exit (1);
		}
		#endif	/* DEBUG */

		result_1 = consultar_1(arg1, arg2, clnt2);
		if (result_1 == (char **) NULL) {
			clnt_perror (clnt2, "call failed");
		}

		#ifndef	DEBUG
		  clnt_destroy (clnt2);
		#endif	 /* DEBUG */
		    result = *result_1;
	}
	return &result;
}

void *
introducirdns_1_svc(nombre arg1, ip arg2,  struct svc_req *rqstp)
{
	static char * result;
	strcpy(redes[util][0],arg1);
	strcpy(redes[util][1],arg2);
	redutil++;
	printf("%s\n", "HA SIDO INTRODUCIDO EL DNS");

	return (void *) &result;
}

void *
eliminardns_1_svc(nombre arg1,  struct svc_req *rqstp)
{
	static char * result;

	int i=0;
	int encontrado=999;

	for(i;i<util;i++){
		if(strcmp(arg1,redes[i][0])==0){
			encontrado=i;
		}
		if(encontrado!=999){ //Tiene nombre y red correctos borramos la posición
			for(encontrado;encontrado<util;encontrado++){
				strcpy(redes[encontrado][0],redes[encontrado+1][0]);
				strcpy(redes[encontrado][1],redes[encontrado+1][1]);
			}
			strcpy(redes[redutil][0],"0");
			strcpy(redes[redutil][1],"0");
			redutil--;
			encontrado=999;
      printf("%s\n", "BORRADO correctamente");
		}
		else{
			printf("%s\n", "NOMBRE NO encontrado");

		}
	}


	return &result;

	return (void *) &result;
}
