/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DNS1.h"


char *
dns1_1(char *host, char *nombre, char *red, char *ip, int codigo)
{
	CLIENT *clnt;
	char * *result_1;
	char * *result_2;
	char * *result_3;
	void *result_4;
	void *result_5;

	if(codigo==0){ //Introducir
		#ifndef	DEBUG
			clnt = clnt_create (host, DNS1, DNSVERS, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
		#endif	/* DEBUG */

		result_1 = introducir_1(nombre, red, ip, clnt);
		if (result_1 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}

		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */

		return *result_1;
	}

	if(codigo==1){

		#ifndef	DEBUG
			clnt = clnt_create (host, DNS1, DNSVERS, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
		#endif	/* DEBUG */
		result_2 = eliminar_1(nombre, red, clnt);
		if (result_2 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */

			return *result_2;
	}

	if(codigo==2){
		#ifndef	DEBUG
			clnt = clnt_create (host, DNS1, DNSVERS, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
		#endif	/* DEBUG */

		result_3 = consultar_1(nombre, red, clnt);
		if (result_3 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */

			return *result_3;
	}

	if(codigo==3){
		#ifndef	DEBUG
			clnt = clnt_create (host, DNS1, DNSVERS, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
		#endif	/* DEBUG */

		result_4=introducirdns_1(nombre, red, clnt);
		if (result_4 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
			return *result_4;
	}

if(codigo==4){
	#ifndef	DEBUG
		clnt = clnt_create (host, DNS1, DNSVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	result_5 = eliminardns_1(eliminardns_1_arg1, clnt);
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
		return *result_5;
}

}


int
main (int argc, char *argv[])
{
	char *host="localhost";
	char *equipo1;
	char *red1;
	int codigo;
	char *ip1;
	char *resultado;
	int comprobacion=0;
	do{

		printf("\nIntroduzca el codigo, 0 para insertar, 1 para borrar, 2 para consultar, 3 introducir DNS, 4 eliminar DNS y 5 para salir. \n");
		scanf("%i", &codigo);

	  if(codigo==5){exit;}

	  printf("Introduzca el nombre del equipo: ");
	  equipo1=malloc(100);
	  scanf("%s", equipo1);

			printf("Introduzca a la red que pertenece, estamos en la Red1: ");
			red1=malloc(103);
	  	scanf("%s", red1);

	  if(codigo==0)
	  {
			printf("Introduzca la ip: ");
	  	ip1=malloc(102);
	  	scanf("%s", ip1);
	    resultado=dns1_1(host,equipo1,red1,ip1,codigo);
	    printf ("%s\n",resultado);

	  }else if(codigo==1){
			resultado=dns1_1(host,equipo1,red1,ip1,codigo);
	    printf ("%s\n",resultado);
	  }else if(codigo==2){
			resultado=dns1_1(host,equipo1,red1,ip1,codigo);
			printf ("%s\n",resultado);
	  }else if(codigo==3){
			dns1_1(host,equipo1,red1,ip1,codigo);
		}else if(codigo==4){
			dns1_1(host,equipo1,red1,ip1,codigo);
		}


	}while(codigo!=5);

exit (0);
}

	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dns1_1 (host);
exit (0);
}
